name: Create Tag

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  createTag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull version from Gradle
        run: |
          echo "TAG_NAME=`gradle properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}'`" >> $GITHUB_ENV
      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            const { TAG_NAME } = process.env
            
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/v${TAG_NAME}`,
              sha: context.sha
            })