name: Main Merge Back

on:
  pull_request:
    types: [opened, reopened]

jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
      - name: Publish Package
        run: gradle test